version: "3"

services:
    app:
        container_name: app1
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - PORT=3000
        volumes:
            - "./src:/usr/src/app"
        ports:
            - "3000:3000"
        links:
            - mongo
        networks:
            - mongo-compose-network
    mongo:
        container_name: mongo1
        image: mongo
        ports:
          - "27017:27017"
        networks:
            - mongo-compose-network
    mongo-express:
            container_name: mongo-express1
            image: mongo-express
            ports:
              - "8081:8081"
            links:
                - mongo
            networks:
                - mongo-compose-network

networks:
    mongo-compose-network:
      driver: bridge
